using Confluent.Kafka;
using Paytently.Models;
using System.Text.Json;

namespace Paytently.Kafka;
/// <summary>
/// This is a method to subscribe to the payment-responses topic, it contains the status of the payment generated by the acquirer
/// </summary>
public class KafkaAwaiterService : IKafkaAwaiterService
{
    private readonly KafkaSettings _kafkaSettings;

    // It gets the kafka settings from appsettings.json, using dependency injection
    public KafkaAwaiterService(KafkaSettings kafkaSettings)
    {
        _kafkaSettings = kafkaSettings;
    }
    public async Task<PaymentResponse?> WaitForResponseAsync(Guid paymentId, int timeout)
    {
        var config = new ConsumerConfig
        {
            BootstrapServers = _kafkaSettings.Broker,
            GroupId = $"paytently-response-{paymentId}",
            AutoOffsetReset = AutoOffsetReset.Earliest
        };
        using var consumer = new ConsumerBuilder<Ignore, string>(config).Build();

        // It subscribes to the requests topic, where the payment requests are being sent
        consumer.Subscribe(_kafkaSettings.ResponseTopic);
        var cancellationTokenSource = new CancellationTokenSource(TimeSpan.FromSeconds(_kafkaSettings.ResponseTimeoutSeconds));

        try
        {
            while (!cancellationTokenSource.IsCancellationRequested)
            {
                // It deserealize the response and return it
                var result = await Task.Run(() => consumer.Consume(cancellationTokenSource.Token));
                var response = JsonSerializer.Deserialize<PaymentResponse>(result.Message.Value);
                if (response != null && response.PaymentId == paymentId)
                {
                    return response;
                }
            }
        }
        // Here we can add different Exceptions to handle different scenarios
        catch (Exception)
        {
            return null;
        }

        return null;
    }
}
